source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1"

gem "just-the-docs", "0.10.1"

group :jekyll_plugins do
  gem "jekyll-tabs", "1.2.1"
  gem "jekyll-github-metadata", "2.16.1"
  gem "jekyll-include-cache", "0.2.1"
  gem "jekyll-sitemap", "1.4.0"
end

