name: CI pipeline

permissions:
  checks: write

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches-ignore:
      - '!master'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ci-pipeline:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        spark:
          - 3.4.1
          - 3.5.0
    env:
      ENV: 'ci'
      SPARK_VERSION: ${{ matrix.spark }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
      - name: Build and test
        run: |
          sbt -java-home "$JAVA_HOME_8_X64" clean scalafmtCheckAll blackCheck flake8 +test pyTest -DsparkVersion="$SPARK_VERSION"
      - name: Publish Unit test results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Unit test results
        if: always()
