name: Publish pipeline

permissions:
  contents: read

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-.*)?'

jobs:
  publish-maven-central-artifacts:
    runs-on: ubuntu-latest

    container:
      image: sbtscala/scala-sbt:eclipse-temurin-17.0.13_11_1.10.5_2.12.20

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        spark:
          - 3.4.1
          - 3.5.0
          - 4.0.0
    env:
      ENV: 'ci'
      SPARK_VERSION: ${{ matrix.spark }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Configure git
        run: git config --global --add safe.directory '*'
      - name: Upload to Maven Central
        run: |
          sbt clean +publishSigned -DsparkVersion="$SPARK_VERSION" sonatypeBundleRelease

  publish-pypi-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          sbt clean pyPublish
