name: Publish pipeline

permissions:
  contents: read

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  publish-maven-central-artifacts:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        spark:
          - 3.1.3
          - 3.2.4
          - 3.3.2
          - 3.4.1
          - 3.5.0
    env:
      ENV: 'ci'
      SPARK_VERSION: ${{ matrix.spark }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Upload to Maven Central
        run: |
          sbt -java-home "$JAVA_HOME_8_X64" clean +publishSigned -DsparkVersion="$SPARK_VERSION" sonatypeBundleRelease

  publish-pypi-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          sbt -java-home "$JAVA_HOME_8_X64" clean pyPublish
